// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eikbnyickboxefbyxodt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpa2JueWlja2JveGVmYnl4b2R0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1ODE2NDAsImV4cCI6MjA3NDE1NzY0MH0.qIhlhk63Kwcp3JHIRBG-ugaQMQCxWtko1jvRbOxKNv0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});